#ifndef GOS_PID_ARDUINO_AUTOTUNING_BASED_LIBRARY_H_
#define GOS_PID_ARDUINO_AUTOTUNING_BASED_LIBRARY_H_

#ifdef ARDUINOBASEDAUTOTUNINGDLL_EXPORTS
#define ARDUINOBASEDPIDAUTOTUNINGDLL_LIBRARY __declspec(dllexport)
#else
#define ARDUINOBASEDPIDAUTOTUNINGDLL_LIBRARY __declspec(dllimport)
#endif

#endif
