#ifndef GOS_PID_ARDUINO_AUTOTUNING_ARRAY_VARIABLES_H_
#define GOS_PID_ARDUINO_AUTOTUNING_ARRAY_VARIABLES_H_

#define ARDUINO_BASE_PID_AUTOTUNING_ARRAY_LAST_INPUT_SIZE 101
#define ARDUINO_BASE_PID_AUTOTUNING_ARRAY_PEAK_SIZE 10
struct ArrayVariables {
  double LastInput[ARDUINO_BASE_PID_AUTOTUNING_ARRAY_LAST_INPUT_SIZE];
  double Peak[ARDUINO_BASE_PID_AUTOTUNING_ARRAY_PEAK_SIZE];
};

#endif
